### ISSUE TITLE
Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by iamluodong** [feross/run-parallel-limit#5]
while tasks very big ,e.g 9000, appear Maximum call stack size exceeded error.

I read source code, the **limit** is available?

**Comment by feross** [comment]
This happens because you're calling the callback function synchronously. You should wrap the callback call in a `process.nextTick(callback)` to prevent the call stack from growing out-of-control.

Does it make sense why this is happening?

We _could_ add code to detect when the callbacks are being called sync, and do the `process.nextTick` automatically, but it would add complexity to the implementation.

**Comment by iamluodong** [comment]
OK,Understand.

I very like **WebTorrent** Project.It is great . I use it download Big File.I found very slow at every startup,because It verify data.
At torrent.js.

```
Torrent.prototype._verifyPieces = function(){
   .
   .
   parallelLimit(self.pieces.map(function (_, index) {
     if (pieceRecorded) 
          self._markVerified(index)       
      cb(null) // should change ---> process.nextTick(cb);
      return;
      }
  }
}
```

**Comment by feross** [comment]
@iamluodong Are you talking about `webtorrent`, the npm package? Or [WebTorrent Desktop](https://webtorrent.io/desktop)?

**Comment by feross** [comment]
Also, the call to `sha1()` in `Torrent.prototype._verifyPieces` is already async, so I don't think it's possible for this issue to arise there. But the "error case" where the piece does not exist on disk _could_ trigger it. Fix here: https://github.com/feross/webtorrent/commit/535fa0264a8e7106266770449de9266e0d598684
